<?php
// mensaje de resultado de configuracion en el home
// function moduloigp_init(){
// 	if(drupal_is_front_page()){
// 	    drupal_set_message(t("Hola mundo! que brujeria es esto?"));
// 	}
// }


/**
* Implements hook_permission().
*Permisos (icono)
*/

function moduloigp_permission() {
	return array(
	'administer moduloigp settings' => array(
	'title' => t('Administer moduloigp configurations'),
	'restrict access' => true,
	)
	);
}


/**
* Formulario de configuración (no funciona)
*
* @return array The form structure.
*/
function moduloigp_admin() {
  $form = array();

  // Algo que configurar
  $form['moduloigp_something'] = array(
  '#type' => 'textfield',
  '#title' => t('Something'),
  '#default_value' => variable_get(‘moduloigp_something’, ""),
  '#size' => 60,
  '#maxlength' => 250,
  '#description' => t("Something"),
  '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
* Implements hook_help().
* Implements ayuda del modulo().
*/
function moduloigp_help ( $path, $arg )
{
  $output=''; // para construir la salida
  switch ( $path )
  {
    case 'admin/help#moduloigp':
      $output .= '<p>' . t('Este es el sector de ayuda para el módulo de prueba para el cndg...') . '</p>';
      break;
  }
  return $output;
}

/**
* Implementation of hook_block().
* Bloques
*/
function moduloigp_block ( $op = 'list', $delta = 0, $edit = array() )
{
  if ( $op == "list")
  {
      $blocks = array();
      $blocks[0]["info"] = t('moduloigp');
      $blocks[1]["info"] = t('New moduloigps');
      return $blocks;
  }
  else if ( $op == "view" )
  {
      $content = '';
      $block = array();
      switch ( $delta )
      {
        case 0:
          $block['subject'] = t('moduloigp');

          $options = array( "attributes" => array("title" => t("Sends a moduloigp message") ) );
          $link = l( t("New moduloigp"), "moduloigp/message", $options );
          $content .= '<div class="link">' . $link . "</div>";
          break;
        case 1:
          $block['subject'] = t('moduloigp Messages');

          $options = array( "attributes" => array("title" => t("Shows moduloigp messages") ) );
          $title = t("There are @total new feeds", array ( '@total' => _moduloigp_count() ) );
          $link = l( $title , "moduloigp/adminmessages", $options );
          $content .= '<div class="link">' . $link . "</div>";
          break;
      }
      $block['content'] = $content;
      return $block;
  }
}
//bloque con un saludo
function moduloigp_block_info(){
  $blocks['hola_mundo'] = array(
      'info'=>'Bloque para saludo Hola mundo'
  );
  return $blocks;
}
function moduloigp_block_view($delta=''){
  switch ($delta) {
    case 'hola_mundo':
      $block['content']=saludo_bienvenida();
      return $block;
  }
}
/*Creacion de formularios*/

function moduloigp_message ()
{
  $content = '';

  $content .= drupal_get_form ( 'moduloigp_message_form' );

  return $content;
}

/*menu hola mundo*/
function moduloigp_menu(){
   $items['saludo/hola-mundo'] = array(
	      'title'=>'Saludo',
        'page callback'=>'saludo_bienvenida', //llama a la funcion saludo_bienvenida()
         // solo pagina sin item en el menu de navegacion
	      'type' => MENU_CALLBACK, //por defecto: MENU_NORMAL_ITEM
        'access callback'=>TRUE,
   );
   //configurar el saludo de nuestro modulo desde el administrador.
   $items['admin/config/content/saludo'] = array(
    'title' => 'Saludar',
    'description' => 'Configurar las opciones para el saludo.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('moduloigp_configuracion'),//llama a la funcion de configuracion en el archivo saludo.admin.inc
    'access arguments' => array('administer site configuration'),
    'file' => 'saludo.admin.inc',
  );
   return $items;
}

function saludo_bienvenida(){
   // $saludo = 'Hola bienvenid@ a mi sitio';
   // return $saludo;
   $variables = array(
       'message' => variable_get('saludo_texto', 'Hola Mundo'),
     );
     return theme('saludar_hola_mundo', $variables);
}

function moduloigp_theme() {
  return array(
    'saludar_hola_mundo' => array(
      'template' => 'saludar-hola-mundo', //tpl.php
    ),
  );
}